DROP TABLE IF EXISTS ACCOUNT_DEMO;

CREATE TABLE ACCOUNT_DEMO
   (
    ACCOUNT_ID NUMBER(10),
	ACCOUNT_NUMBER VARCHAR2(30),
	NAME VARCHAR2(50),
	DESCRIPTION VARCHAR2(250),
	ACCOUNT_TYPE VARCHAR2(50)
);

INSERT INTO ACCOUNT_DEMO (ACCOUNT_ID, ACCOUNT_NUMBER, NAME, DESCRIPTION, ACCOUNT_TYPE)
VALUES(1, '12233455445554', 'Cuenta de Ahorros', 'Demo cuenta from multitenant microservices # 1', 'AHORROS');
INSERT INTO ACCOUNT_DEMO (ACCOUNT_ID, ACCOUNT_NUMBER, NAME, DESCRIPTION, ACCOUNT_TYPE)
VALUES(2, '12233455145214', 'Cuenta Corriente', 'Demo cuenta from multitenant microservices # 2', 'CORRIENTE');
INSERT INTO ACCOUNT_DEMO (ACCOUNT_ID, ACCOUNT_NUMBER, NAME, DESCRIPTION, ACCOUNT_TYPE)
VALUES(3, '12233955145210', 'Cuenta Ahorros', 'Demo cuenta from multitenant microservices # 3', 'AHORROS');
INSERT INTO ACCOUNT_DEMO (ACCOUNT_ID, ACCOUNT_NUMBER, NAME, DESCRIPTION, ACCOUNT_TYPE)
VALUES(4, '12233955145210', 'Cuenta Ahorros', 'Demo cuenta from multitenant microservices # 4', 'AHORROS');
INSERT INTO ACCOUNT_DEMO (ACCOUNT_ID, ACCOUNT_NUMBER, NAME, DESCRIPTION, ACCOUNT_TYPE)
VALUES(5, '12233955141412', 'Cuenta Ahorros', 'Demo cuenta from multitenant microservices # 5', 'AHORROS');
